DO $$
BEGIN
  IF (SELECT COUNT(*) FROM questions WHERE team_id IS NULL) = 0 THEN
    INSERT INTO questions (team_id, pillar, question_text, input_type, options, "order", impact_weight, frequency_class, is_core, is_required, source, follow_up_logic) VALUES
    -- WELLNESS
    (NULL, 'wellness', 'I have sustainable energy levels throughout the work week.', 'likert_5', NULL, 1, 1.2, 'core', true, true, 'WHO-5 adapted', '{"trigger":"lte","threshold":2,"question":"What''s draining your energy the most?","type":"multi_select","options":["Workload","Sleep","Personal issues","Unclear priorities","Team conflict","Other"]}'),
    (NULL, 'wellness', 'I am able to maintain a healthy work-life balance.', 'likert_5', NULL, 2, 1.0, 'high', false, true, 'HeartCount Pulse', '{"trigger":"lte","threshold":2,"question":"What is the main factor affecting your balance?","type":"open_text"}'),
    (NULL, 'wellness', 'I feel I can take time off when I need it without guilt.', 'likert_5', NULL, 3, 0.8, 'standard', false, true, 'Burnout research / APA', '{"trigger":"lte","threshold":2,"question":"What makes it hard for you to take time off?","type":"open_text"}'),
    (NULL, 'wellness', 'I have been feeling stressed or overwhelmed in the past two weeks.', 'frequency_5', ARRAY['Not at all','Rarely','Sometimes','Often','Almost always'], 4, 1.2, 'high', false, true, 'MBI / WHO Burnout', '{"trigger":"gte","threshold":4,"question":"Would you like to connect with support resources?","type":"yes_no"}'),
    (NULL, 'wellness', 'My current workload feels manageable.', 'traffic_light', ARRAY['Just right','Slightly too much or too little','Unmanageable'], 5, 1.0, 'standard', false, true, 'WHO Burnout adapted', NULL),
    -- ALIGNMENT
    (NULL, 'alignment', 'I understand how my current work connects to the team''s goals.', 'likert_5', NULL, 6, 1.2, 'core', true, true, 'Gallup Q01', '{"trigger":"lte","threshold":3,"question":"What feels unclear right now?","type":"multi_select","options":["My role","Team goals","Company priorities","Success metrics","Who to ask"]}'),
    (NULL, 'alignment', 'I am clear on what success looks like for my current projects.', 'likert_5', NULL, 7, 1.0, 'high', false, true, 'Spotify Mission', '{"trigger":"lte","threshold":2,"question":"What''s making success criteria unclear for you right now?","type":"open_text"}'),
    (NULL, 'alignment', 'I feel our team''s priorities are well-defined.', 'likert_5', NULL, 8, 1.0, 'standard', false, true, 'Atlassian Health Monitor', '{"trigger":"lte","threshold":2,"question":"What feels most unclear or competing right now?","type":"open_text"}'),
    (NULL, 'alignment', 'I feel my opinions count when decisions are made.', 'likert_5', NULL, 9, 0.8, 'standard', false, true, 'Gallup Q07', '{"trigger":"lte","threshold":2,"question":"In what area do you wish you had more input?","type":"open_text"}'),
    (NULL, 'alignment', 'I have the materials and resources I need to do my work right.', 'likert_5', NULL, 10, 0.8, 'standard', false, true, 'Gallup Q02', '{"trigger":"lte","threshold":3,"question":"What are you missing?","type":"multi_select","options":["Hardware","Software/tools","Access/permissions","Documentation","Budget"]}'),
    -- MANAGEMENT
    (NULL, 'management', 'My lead provides feedback that helps me improve.', 'likert_5', NULL, 11, 1.2, 'core', true, true, 'Gallup Q05 adapted', '{"trigger":"lte","threshold":2,"question":"What would make feedback more useful?","type":"multi_select","options":["More specific examples","Written follow-up","Tied to goals","More timely"]}'),
    (NULL, 'management', 'I feel comfortable raising concerns with my lead.', 'likert_5', NULL, 12, 1.0, 'high', false, true, 'Google re:Work', '{"trigger":"lte","threshold":2,"question":"What would help you feel safer raising concerns?","type":"open_text"}'),
    (NULL, 'management', 'My lead supports my professional development.', 'likert_5', NULL, 13, 1.0, 'standard', false, true, '15Five', '{"trigger":"lte","threshold":2,"question":"What kind of development support would be most helpful?","type":"multi_select","options":["Mentorship","Training budget","Stretch projects","Career conversations","Conference attendance"]}'),
    (NULL, 'management', 'I trust my lead to advocate for the team.', 'likert_5', NULL, 14, 0.8, 'standard', false, true, 'Officevibe', '{"trigger":"lte","threshold":2,"question":"What''s making it hard to trust in advocacy right now?","type":"open_text"}'),
    (NULL, 'management', 'My 1:1s are valuable and well-structured.', 'likert_5', NULL, 15, 0.8, 'deep', false, true, 'Lattice', '{"trigger":"lte","threshold":2,"question":"What would make your 1:1s more valuable?","type":"multi_select","options":["Clear agenda","More frequent","More actionable","Better follow-through","More coaching"]}'),
    -- GROWTH
    (NULL, 'growth', 'I am learning new skills in my current role.', 'likert_5', NULL, 16, 1.0, 'core', true, true, 'Gallup Q12 adapted', '{"trigger":"lte","threshold":3,"question":"What type of growth would be most valuable to you?","type":"multi_select","options":["Technical skills","Leadership","Cross-functional","Mentorship","Conferences","Other"]}'),
    (NULL, 'growth', 'I have access to the resources I need to grow professionally.', 'likert_5', NULL, 17, 1.0, 'high', false, true, 'Leapsome', '{"trigger":"lte","threshold":2,"question":"What resources are you missing?","type":"multi_select","options":["Learning platform access","Budget for courses","Time for learning","Mentorship","Internal knowledge sharing"]}'),
    (NULL, 'growth', 'I feel challenged by my work in a healthy way.', 'traffic_light', ARRAY['Just right','Under-challenged or Over-challenged','Completely misaligned'], 18, 0.8, 'standard', false, true, 'Leapsome', NULL),
    (NULL, 'growth', 'I have a clear sense of my career path here.', 'likert_5', NULL, 19, 1.0, 'standard', false, true, 'Lattice / Culture Amp', '{"trigger":"lte","threshold":2,"question":"What would help you see a clearer path?","type":"multi_select","options":["Career framework","Manager 1:1s","Internal job board","Skill assessments"]}'),
    (NULL, 'growth', 'I''ve had opportunities to share or teach what I know.', 'yes_no', NULL, 20, 0.6, 'deep', false, true, 'Gallup Q03', '{"trigger":"lte","threshold":0,"question":"What knowledge would you like to share with the team?","type":"open_text"}'),
    -- DESIGN COURAGE
    (NULL, 'design_courage', 'I feel safe taking creative risks in my work.', 'likert_5', NULL, 21, 1.2, 'core', true, true, 'Google re:Work Psych. Safety', '{"trigger":"lte","threshold":2,"question":"What''s holding you back from taking creative risks?","type":"multi_select","options":["Fear of judgment","Tight deadlines","Unclear expectations","Past negative experience","Lack of support"]}'),
    (NULL, 'design_courage', 'Our team holds itself to high craft standards.', 'likert_5', NULL, 22, 1.0, 'high', false, true, 'Artkai internal', '{"trigger":"lte","threshold":2,"question":"Where do you see craft standards slipping?","type":"open_text"}'),
    (NULL, 'design_courage', 'I can push back on requirements when I believe it''s right for the user.', 'likert_5', NULL, 23, 1.0, 'standard', false, true, 'NNGroup UX Research', '{"trigger":"lte","threshold":2,"question":"What makes it difficult to advocate for user needs?","type":"open_text"}'),
    (NULL, 'design_courage', 'We make time for exploration and experimentation.', 'likert_5', NULL, 24, 0.8, 'standard', false, true, 'Spotify Squad Health', '{"trigger":"lte","threshold":2,"question":"What''s preventing exploration time?","type":"multi_select","options":["Too many deliverables","No allocated time","Client pressure","Unclear value of exploration","Lack of tools"]}'),
    (NULL, 'design_courage', 'Honest design critique is welcomed and practiced on this team.', 'likert_5', NULL, 25, 0.8, 'deep', false, true, 'Artkai internal', '{"trigger":"lte","threshold":2,"question":"What would make design critique feel safer or more productive?","type":"open_text"}'),
    -- COLLABORATION
    (NULL, 'collaboration', 'My teammates are responsive and supportive.', 'likert_5', NULL, 26, 1.2, 'core', true, true, 'Gallup Q10 adapted', '{"trigger":"lte","threshold":2,"question":"Where do you feel support is lacking?","type":"open_text"}'),
    (NULL, 'collaboration', 'I can easily get the information I need from other teams.', 'likert_5', NULL, 27, 1.0, 'high', false, true, 'Atlassian', '{"trigger":"lte","threshold":2,"question":"What information is hardest to get, and from where?","type":"open_text"}'),
    (NULL, 'collaboration', 'Cross-functional collaboration is smooth and productive.', 'likert_5', NULL, 28, 1.0, 'standard', false, true, 'Spotify Squad Health', '{"trigger":"lte","threshold":2,"question":"What''s causing friction in cross-functional work?","type":"multi_select","options":["Misaligned priorities","Communication gaps","Tool differences","Unclear ownership","Scheduling conflicts"]}'),
    (NULL, 'collaboration', 'We resolve disagreements constructively.', 'likert_5', NULL, 29, 0.8, 'standard', false, true, 'Atlassian', '{"trigger":"lte","threshold":2,"question":"Is there an unresolved conflict affecting your work right now?","type":"yes_no"}'),
    (NULL, 'collaboration', 'Knowledge is shared openly within the team.', 'likert_5', NULL, 30, 0.6, 'deep', false, true, 'Culture Amp', '{"trigger":"lte","threshold":2,"question":"What knowledge do you wish was shared more openly?","type":"open_text"}'),
    -- RECOGNITION
    (NULL, 'recognition', 'I feel my contributions are recognized.', 'likert_5', NULL, 31, 1.2, 'core', true, true, 'Gallup Q04', '{"trigger":"lte","threshold":2,"question":"What kind of recognition would feel most meaningful?","type":"multi_select","options":["Public shout-out","Private message","Bonus/reward","Peer recognition","Manager praise"]}'),
    (NULL, 'recognition', 'I can see the impact of my work on real users or outcomes.', 'likert_5', NULL, 32, 1.0, 'high', false, true, '15Five / Officevibe', '{"trigger":"lte","threshold":2,"question":"What would help you see the impact of your work?","type":"multi_select","options":["User feedback sessions","Analytics dashboards","Post-launch reviews","Client testimonials","Impact reports"]}'),
    (NULL, 'recognition', 'I feel valued as a member of this team.', 'likert_5', NULL, 33, 1.0, 'standard', false, true, 'Culture Amp', '{"trigger":"lte","threshold":2,"question":"What would help you feel more valued?","type":"open_text"}'),
    (NULL, 'recognition', 'My work is visible beyond my immediate team.', 'likert_5', NULL, 34, 0.8, 'standard', false, true, 'Officevibe', '{"trigger":"lte","threshold":2,"question":"What would help make your work more visible?","type":"multi_select","options":["Showcase presentations","Cross-team demos","Internal newsletter","Leadership exposure","Portfolio sharing"]}'),
    (NULL, 'recognition', 'I am proud of what we''ve shipped recently.', 'likert_5', NULL, 35, 0.6, 'deep', false, true, 'Artkai internal', '{"trigger":"lte","threshold":2,"question":"What''s dampening your pride in recent work?","type":"open_text"}'),
    -- BELONGING
    (NULL, 'belonging', 'I feel I can be myself at work.', 'likert_5', NULL, 36, 1.2, 'core', true, true, 'DEIB / Officevibe', '{"trigger":"lte","threshold":2,"question":"What makes it hard to be yourself at work?","type":"open_text"}'),
    (NULL, 'belonging', 'Diverse perspectives are genuinely valued on this team.', 'likert_5', NULL, 37, 1.0, 'high', false, true, 'Culture Amp', '{"trigger":"lte","threshold":2,"question":"Where do you see diversity of thought being undervalued?","type":"open_text"}'),
    (NULL, 'belonging', 'I feel included in decisions that affect my work.', 'likert_5', NULL, 38, 1.0, 'standard', false, true, 'Gallup Q07', '{"trigger":"lte","threshold":2,"question":"Which decisions do you feel left out of?","type":"open_text"}'),
    (NULL, 'belonging', 'I feel a sense of connection with my teammates.', 'likert_5', NULL, 39, 0.8, 'standard', false, true, 'Gallup Q10', '{"trigger":"lte","threshold":2,"question":"What would help you feel more connected?","type":"multi_select","options":["Team socials","Pair work","Shared rituals","Smaller group chats","More 1:1s"]}'),
    (NULL, 'belonging', 'My voice matters in team discussions.', 'likert_5', NULL, 40, 0.6, 'deep', false, true, 'Officevibe', '{"trigger":"lte","threshold":2,"question":"What would help your voice be heard more?","type":"multi_select","options":["Smaller group settings","Async input channels","Structured turn-taking","Anonymous feedback","More facilitated discussions"]}');
  END IF;
END $$;
