// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/AtmosphericCard.tsx": () => import("../components/mockups/login-variants/AtmosphericCard.tsx"),
  "./components/mockups/login-variants/PolishedMinimal.tsx": () => import("../components/mockups/login-variants/PolishedMinimal.tsx"),
  "./components/mockups/settings-reimagined/SettingsReimaginedV1.tsx": () => import("../components/mockups/settings-reimagined/SettingsReimaginedV1.tsx")
};
